FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# even not necessary, still recommended to leave it here. For example, production Dockerfile still need it
COPY . . 

CMD ["npm", "run", "start"]