# a quality-of-life script file to get rid of long docker run command such as -p -v
version: '3'

services:
  web:
    build:
      # dont add `.` when specifying file, just use the file name here.
      # so here, we want to use "Dockerfile.dev"
      # the file path will be specified in the context
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      # the /app in container with be a file reference of local file
      - .:/app
    command: ["npm", "run", "start"]
  tests:
      # dont add `.` when specifying file, just use the file name here.
      # so here, we want to use "Dockerfile.dev"
      # the file path will be specified in the context
    build:  
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]