# runnign a docker
sudo: required # we need super use permission

services: 
  - docker # install a copy of docker

script:
  - cd frontend

before_install:
  - docker build -t ultraspicy/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true ultraspicy/docker-react npm run test 

# build image using Dockerfile.DEV 

# how to run test suite

# how to deploy the project 