# Travis flows
# - specify docker as a dependency
# - build test version of react project
# - run tests (only run react for demo)
# - build prod version of all projects
# - push all to docker hub
# - tell elastic beanstalk to update
language: generic 
sudo: required 

# specify docker as a dependency
services:
  - docker

# build test version of react project
before_install:
  - cd complex 
  - docker build -t ultraspicy/react-test -f ./client/Dockerfile.dev ./client

# run tests (only run react for demo)
script:
  - docker run -e CI=true ultraspicy/react-test npm test

# build prod version of all projects
after_success:
  - docker build -t ultraspicy/multi-client ./client
  - docker build -t ultraspicy/multi-nginx ./nginx
  - docker build -t ultraspicy/multi-server ./server
  - docker build -t ultraspicy/multi-worker ./worker
  # take those images and push them to docker hub
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images
  - docker push ultraspicy/multi-client
  - docker push ultraspicy/multi-nginx
  - docker push ultraspicy/multi-server
  - docker push ultraspicy/multi-worker
